### ISSUE TITLE
Is there any way to change the style of the output PDF ?

### ISSUE THREAD

**Issue by holidayworking** [orzih/mkdocs-with-pdf#1]
I want to change the PDF footer.

I added [extra_css](https://www.mkdocs.org/user-guide/configuration/#extra_css) such as the following:

```css
@page {
  @bottom-center {
    font-size: 6pt;
    content: string(copyright);
  }

  @bottom-right {
    font-size: 8pt;
    content: '- 'counter(page)'/'counter(pages)' -';
  }
}
```

But it didn't change.

Is there any way to change the style of the output PDF ?

**Comment by orzih** [comment]
This plugin adds the style of [report-print](https://github.com/orzih/mkdocs-with-pdf/tree/master/mkdocs_with_pdf/styles) after "extra_css".
You can try this:
```css
@page {
  @bottom-center {
    font-size: 6pt !important;
    content: string(copyright) !important;
  }

  @bottom-right {
    font-size: 8pt !important;
    content: '- 'counter(page)'/'counter(pages)' -' !important;
  }
}
```

have fun.
