### ISSUE TITLE
How to change the title of the table of content

### ISSUE THREAD

**Issue by jaixan** [orzih/mkdocs-with-pdf#11]
Hi, 

When generating a pdf, I would like to change the phrase "table of content" for its French equivalent "Table des matières". I tried to change it with CSS : 

```
article#doc-toc > h1 {
  content:"Table des matières" !important;
}
```

However it did not change. Please advise.

**Comment by orzih** [comment]
I add new option `toc_title` in v0.4.0.
Please try the following - edit `mkdocs.yml`.
```yaml
plugins:
    - with-pdf
        toc_title: Table des matières
```
