### ISSUE TITLE
SVG Image not rendered correctly in pdf

### ISSUE THREAD

**Issue by chvdfSi** [orzih/mkdocs-with-pdf#111]
All my SVG images look like they are shifted to the left a bit when rendering them into the pdf. On the web page everything looks normal. 

In the screen shot the upper one is from the web page and the lower from the pdf.

![PDFRenderSVG](https://user-images.githubusercontent.com/92139758/169287203-acdf08da-a041-417d-b386-41a383f0bebb.png)

mkdoc.yml
``` yml
site_name: Design Documentation

plugins:
    - with-pdf:
        author: Someone
        #copyright: ANY TEXT
        #
        cover: true
        #back_cover: true
        cover_title: My awesome Document
        cover_subtitle: Observe
        #custom_template_path: TEMPLATES PATH
        #
        toc_title: Content
        #heading_shift: false
        toc_level: 3
        ordered_chapter_level: 3
        output_path: DesignDocumentation.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        debug_html: true
        #show_anchors: true
        #verbose: true
```
I also tried switching to chrome to render the pdf, but sadly with the same result.
All diagrams are exported as SVGs beforehand and included in the markdown like `![Class diagram](_img/class_diagram.svg "Class diagram")`
