### ISSUE TITLE
use theme colors for pdf generation

### ISSUE THREAD

**Issue by DanielHabenicht** [orzih/mkdocs-with-pdf#119]
The colors used for TOC and underlines of the headlines are currently statically set: 
![image](https://user-images.githubusercontent.com/13590797/180272935-72d3cd7f-bbca-4dcb-a7d2-8c507560b14b.png)
![image](https://user-images.githubusercontent.com/13590797/180273006-94c72a00-ed1b-4a69-b8c4-8d546efd3712.png)

Instead of displaying the theme color `inidigo-blue` they use the colors set here: 
https://github.com/orzih/mkdocs-with-pdf/blob/f2e78d8c8ecb505636ba31a4830646038a78accd/mkdocs_with_pdf/styles/_heading.scss#L1-L12
https://github.com/orzih/mkdocs-with-pdf/blob/f2e78d8c8ecb505636ba31a4830646038a78accd/mkdocs_with_pdf/styles/_toc.scss#L42

It would be great if theses colors could either be specified in the plugin settings or use global defaults.

Workaround: 
```css
// Styling done by Material for Mkdocs: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors
:root > * {
	--md-primary-fg-color: #e20074;
	--md-primary-fg-color--light: #ecb7b7;
	--md-primary-fg-color--dark: #9e0051;
}

#doc-toc * {
	border-color: var(--md-primary-fg-color) !important;
}

article h1,
article h2,
article h3 {
	border-color: var(--md-primary-fg-color)!important;
}
```

**Comment by ojacques** [comment]
@DanielHabenicht I know this is not the original request, but for the records, I was able to customize the color of the lines below the titles by adding a `templates/styles.scss` file with the following content:

```css
$color: #004491;

@media print {
  
  .md-typeset h1 {border-bottom: 2px solid $color;  } // for material theme
  article h1 { border-bottom: 2px solid $color;  } // other theme

  .md-typeset h2 {border-bottom: 1px solid $color;  } // for material theme
  article h2 { border-bottom: 1px solid $color;  } // other theme

  .md-typeset h3 {border-bottom: 0.5px solid $color;  } // for material theme
  article h3 { border-bottom: 0.5px solid $color;  } // other theme

}
```
