### ISSUE TITLE
Horizontal line is not displayed in PDF

### ISSUE THREAD

**Issue by JanoschDeurer** [orzih/mkdocs-with-pdf#13]
I'm using material for Mkdocs. In markdown a horizontal line can be added with the following code:
```
---
```

it looks like this

---
this is not rendered in the PDF.

**Comment by orzih** [comment]
Please check your css such as `css/pdf-print.css`.
and remove or modify `hr` entry:
```css
@media print {
    hr {
        display: none;
    }
}
```
