### ISSUE TITLE
Admonitions not displayed correctly

### ISSUE THREAD

**Issue by Susi-SiSo** [orzih/mkdocs-with-pdf#161]
In the PDF generated with this plugin, the admonitions are not displayed correctly: the icon is displayed over the text (see attached screenshot). 

How can I fix this?
Thx.

![admonitions-problem-pdf](https://github.com/user-attachments/assets/c1c2ed69-cf86-427c-b0d6-6b28a07a9c53)

**Comment by Thiti517** [comment]
I had the same type of issue and found a fix in issue #89. Can you check if it works for you?

to summarize...

1. create a css file (`docs/assets/styles/pdf-admonition-fix.css`) and fill it with this code (from issue #89)
``` css
@media print {
    /* admonition overrides */

    /* admonition icon */
    .md-typeset :is(.admonition-title,summary):before {
      top: 0.6rem;
      left: 0.6rem;
    }

    /* left border
    .md-typeset :is(.admonition,details) {
      border-left-width: 0.1rem;
      padding: 0rem 0rem 0rem 0rem;
      margin-left: 1rem;
    }

    [dir=ltr] .md-typeset :is(.admonition,details) {
      margin-left: 1rem;
    }

    html .md-typeset :is(.admonition,details)>:last-child {
      margin-left: 0.6rem;
    }
 */
}
```

2. add the path to file as a new `extra_css` entry in `mkdocs.yml` :
``` yaml
site_name: My Docs
...
extra_css:
  - 'assets/styles/pdf-admonition-fix.css'
...
```

All credits goes to :

- cmaurer
- santaimpersonator
