### ISSUE TITLE
Font used in language-specific code block is not monospaced

### ISSUE THREAD

**Issue by madjxatw** [orzih/mkdocs-with-pdf#163]
Contents in language-specific code block are not rendered with the specified monospace font, while the inline code and code block without language specified are displayed as expected.

I have the following in my `pdf-print.css` file:

```css
@media print {
  * {
    font-family: Inter, serif !important;
  }

  code, pre code {
    font-family: "Source Code Pro", Consolas, monospace !important;
  }
}
```
