### ISSUE TITLE
Long tables are rendered on a new page

### ISSUE THREAD

**Issue by JanoschDeurer** [orzih/mkdocs-with-pdf#30]
If you have a table that is longer than a single page, the table is always starting on a separate page even if the content above the table consists only of a single sentence. I know it's not easy to define when a pagebreak makes sense and when it doesn't... Maybe you have an idea on how to improve this.

**Comment by orzih** [comment]
Try adding the following to your custom CSS:

``` css
article table {
  page-break-before: auto !important;
  page-break-inside: auto !important;
}
```
---

now defaults:

https://github.com/orzih/mkdocs-with-pdf/blob/9abc9785abef75bf82c28391daec29609d049b30/mkdocs_with_pdf/styles/_paging.scss#L58-L65
