### ISSUE TITLE
Color of level 1 heading not changeable

### ISSUE THREAD

**Issue by erwini** [orzih/mkdocs-with-pdf#37]
I want to change the textcolor from grey to another color for the level1 heading (h1). I was able to do it for h2 to h6 with the help of styles.scss in the template directory introduced in version `0.8.0`
```
$tmag: #0f0;
h1 { color: $tmag;}
article h1,h2,h3,h4,h5,h6 {color: $tmag;}
```
any hint ?

**Comment by orzih** [comment]
try this:

```scss
$tmag: #0f0;
.md-typeset h1 { color: $tmag; }

// or

@media print {
  .md-typeset h1 { color: $tmag; } // for material theme
  article h1 { color: $tmag; } // other theme
}

// or

.md-typeset h1 { color: $tmag !important; } // for material theme
article h1 { color: $tmag !important; } // other theme
```
