### ISSUE TITLE
How to put string in `cover_title` or `cover_subtitle` so that it split lines.

### ISSUE THREAD

**Issue by kittiu** [orzih/mkdocs-with-pdf#47]
For example, I wan the title to be,
```
This is document
for
Company A
```
And not 
```This is document for Company A```

I try everything, using |, \n, \newline, \n\n, 2 break lines, <br>, and they are not working.

**Comment by orzih** [comment]
Hi kittiu.
This plugin is not control line breaks. 
However, you can use `custom_template_path` option and custom `cover.html`.

e.g.

1. edit `mkdocs.yml`
    ```yml
    plugins:
      - search
      - with-pdf:
          custom_template_path: custom_pdf
    ```
2. create `custom_pdf` directory on same place `mkdocs.yml`, and create `custom_pdf/cover.html.j2`.
    samples [default_cover.html.j2](https://github.com/orzih/mkdocs-with-pdf/blob/master/mkdocs_with_pdf/templates/default_cover.html.j2)

...and put 'custom_pdf/styles.scss' if you want.
