### ISSUE TITLE
How to increase font-size for text and headings?

### ISSUE THREAD

**Issue by alexander-matthiesen** [orzih/mkdocs-with-pdf#51]
How can the font size be increased globally?
Especially the headings are pretty small when there are h5 or h6 headings.

**Comment by orzih** [comment]
Hi @alexander-matthiesen.

Are you using a material theme?
See [material theme's default](https://github.com/squidfunk/mkdocs-material/blob/1e812c61461189f563d841b921a2f054e641610d/src/assets/stylesheets/main/_typeset.scss#L62-L73).

e.g. try adding the following to your custom CSS:
```css
@print {
  .md-typeset {
    font-size: 0.8rem !important;
  }
  .md-typeset h4,
  .md-typeset h5,
  .md-typeset h6 {
    font-size: 1rem;
  }
}
```
