### ISSUE TITLE
how to export B5 instead of  A4

### ISSUE THREAD

**Issue by yuruotong1** [orzih/mkdocs-with-pdf#57]
how to export B5 instead of  A4

**Comment by orzih** [comment]
Try adding the following to your custom style:

```css
@page {
  size: b5 portrait !important;
}
```

---

See also:

https://github.com/orzih/mkdocs-with-pdf/blob/f2e78d8c8ecb505636ba31a4830646038a78accd/mkdocs_with_pdf/styles/_paging.scss#L1-L3

**Comment by yuruotong1** [comment]
> Try adding the following to your custom style:
> 
> ```css
> @page {
>   size: b5 portrait !important;
> }
> ```
> 
> See also:
> 
> https://github.com/orzih/mkdocs-with-pdf/blob/f2e78d8c8ecb505636ba31a4830646038a78accd/mkdocs_with_pdf/styles/_paging.scss#L1-L3

thanks, do you know how to change font size

**Comment by orzih** [comment]
e.g.

```css
@media print {
  html { font-size: 95%; }
  body { font-size: 10.5pt; }
  article { font-size: 0.8rem; line-height: 1.6; }
}
```

and, See `debug_html` option.
