### ISSUE TITLE
custom admonition type in PDF

### ISSUE THREAD

**Issue by cooper-lzy** [orzih/mkdocs-with-pdf#61]
The custom admonition type in PDF cannot be displayed, only the default style is displayed. Please instruct me how to set it?
![image](https://user-images.githubusercontent.com/78672629/120259790-2893fe00-c2c7-11eb-9b98-23bd6c9d5963.png)
![image](https://user-images.githubusercontent.com/78672629/120259815-35185680-c2c7-11eb-9c1c-4a456f90e4b6.png)

**Comment by orzih** [comment]
Hi @cooper-lzy.

Now, `mkdocs-material` generates style is:
```css
.md-typeset .note>summary:before {
  background-color: #448aff;
  mask-image: var(--md-admonition-icon--note);
  ...
}
```

But, WeasyPrint not supports `mask-image`.
This plugin set custom css.

To customize the icon, you need to set it yourself in your styles, e.g:
```css
@media print
.md-typeset .note > .admonition-title::before, .md-typeset .note > summary::before {
    background-image:  url("data:image/svg+xml;charset=utf8,%3Csvg viewBox=....") !important;
}
```

---

See this polyfill:

https://github.com/orzih/mkdocs-with-pdf/blob/65f36ba383b022627df54db00d885d9e06dedd09/custum_style_src/material-polyfills/src/stylesheets/extensions/_admonition.scss#L62-L76
