### ISSUE TITLE
tabs from "tabbed from PyMdown Extensions" does not get processed correctly

### ISSUE THREAD

**Issue by honschi19** [orzih/mkdocs-with-pdf#66]
the pdf generator was working nice until we decided to use the tabbed extension.
https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/

The issue is simple 
-the content from other tab then the first tab is not rendered, 
- if the TAB content is longer then one page then then it is cut of after first page

would be nice to see the support for that.

**Comment by orzih** [comment]
Hi @honschi19.

I think this problem is due to a "page break rules" mismatch.

e.g.: Try adding the following to your custom CSS:

``` css
article div.tabbed-content--wrap {
  page-break-inside: auto !important;
}
article div.tabbed-content--wrap * {
  page-break-before: auto !important;
  page-break-inside: auto !important;
}
```

and, check to build with `debug_html` option.

---

See also: this plugin defaults: 

https://github.com/orzih/mkdocs-with-pdf/blob/dce2c65004d979e4abc310e61178ff859cc5762e/mkdocs_with_pdf/styles/_paging.scss#L58-L88

**Comment by honschi19** [comment]
hi @orzih 

thanks. I tried it, but no success. 

When I use weasyprint directly it does the right page breaks as expected also on the tabbed content. 

Just out of curiosity then I put `auto` and then `inherit` to each of the parameters specified in the default styles of the package in my local .scss. But the result for the tabs did not change. I tried couple of other settings but the tabs did not change. I changed the color of the font just to confirm the .scss is being loaded. The result on the tabs is not changing regardless on what I change.

tnx

**Comment by orzih** [comment]
**page-break** full reset sample: (`SCSS` format)

```scss
article,
section + section {
  page-break-before: always;

  %headings,
  img {
    page-break-after: auto !important;
    page-break-inside: auto !important;
  }

  a,
  blockquote,
  table,
  ul,
  ol {
    page-break-before: auto !important;
    page-break-inside: auto !important;
  }

  pre,
  dt + dd {
    page-break-before: auto !important;
  }

  %headings + ul,
  %headings + ol {
    page-break-inside: auto !important;
  }

  div.admonition {
    page-break-inside: auto !important;
  }

  div.tabbed-content--wrap {
    page-break-inside: auto !important;
  }

  * + div.highlight,
  * + div.tabbed-set {
    page-break-before: auto !important;
  }
}
```
