### ISSUE TITLE
Exclude a single page?

### ISSUE THREAD

**Issue by jimlyas** [orzih/mkdocs-with-pdf#69]
How to exclude a single page?

For example, i have a landing page in my docs folder with directory `docs/index.md`.

And i want to exlude that in my generated PDF? How to do that?

The sample only show us how to exclude folder.

Thanks in advance @orzih

**Comment by orzih** [comment]
Hi @jimlyas.

Try it with a regular expression pattern: e.g. 

- `^$`
- `^index.html$`

**Comment by jimlyas** [comment]
Still not working:
![image](https://user-images.githubusercontent.com/33854739/127428226-d0e97863-3448-416c-bd40-f4220fb39daf.png)
the landing page still included in the pdf file

my configuration:
```yml
with-pdf:
      cover: true
      back_cover: true
      cover_subtitle: A guideline for developing Android Application in Telkom DEV
      cover_logo: assets/icon/512.png
      toc_level: 3
      exclude_pages:
        - 'javadocs/'
        - 'snippets/'
        - '^index.html$'
      output_path: guideline.pdf
```

**Comment by orzih** [comment]
Please check `use_directory_urls` option.

```yml
use_directory_urls: true

plugins:
  - with-pdf:
      exclude_pages:
        - ^$
```

```yml
use_directory_urls: false

plugins:
  - with-pdf:
      exclude_pages:
        - ^index.html$
```
