### ISSUE TITLE
Admonitions do not render in PDF output - mkdocs-material v8.0.2

### ISSUE THREAD

**Issue by Valastiri** [orzih/mkdocs-with-pdf#89]
When building a PDF with version 8.0.2 from mk-material the output of the admonitions markdown extension is broken.

Sample from v7.3.6
![image](https://user-images.githubusercontent.com/1619968/144130642-60c199c9-4789-44a8-89b6-6da911343be7.png)

Sample with v8.0.2
![image](https://user-images.githubusercontent.com/1619968/144130888-154ec773-60b9-4023-a585-9bdebea6e960.png)

No existing changes were made to any configs beyond updating material version.

**Comment by fottsia** [comment]
We're facing the same issue, so currently we have to downgrade mkdocs-material every time we build the .pdf.

**Comment by jacobswe** [comment]
Any progress on this? I am holding off on upgrading until we have some sort of fix for this

**Comment by Valastiri** [comment]
@jacobswe I think it's just best to run on an older build for the pdf export and setup a special case *.yml. I was planning on doing this for the repo I maintain just haven't gotten around to it due to lists being a bit wonky.

**Comment by cmaurer** [comment]
This appears to be a css issue.  I was able to get decent looking admonitions by overriding the css with `extra_sass`.


Pipefile
```
libsass = "*"
```

mkdocs.yml
```yaml
plugins:
  - extra-sass
```

extra_sass/style.css.scss
```css
@media print {
    // admonition overrides

    // admonition icon
    .md-typeset :is(.admonition-title,summary):before {
      top: 0.6rem;
      left: 0.6rem;
    }

    // left border
    .md-typeset :is(.admonition,details) {
      border-left-width: 0.1rem;
      padding: 0rem 0rem 0rem 0rem;
      margin-left: 1rem;
    }

    [dir=ltr] .md-typeset :is(.admonition,details) {
      margin-left: 1rem;
    }

    html .md-typeset :is(.admonition,details)>:last-child {
      margin-left: 0.6rem;
    }

}
```

**Comment by mudgen** [comment]
@cmaurer I made the same changes you did but none of the styling show for my admonitions in the PDF.  What am I missing?

**Comment by santaimpersonator** [comment]
I've also run into this issue and would like to add-on problems rendering collapsible callouts:
* The suggested modifications from @cmaurer didn't seem to work for me

Python packages:
* mkdocs-material v8.5.7
* mkdocs-with-pdf v0.9.3

Rendering Issues:
* Text is rendered externally:
  ```
  ??? note "Note: Charging PD Devices"
  When a PD device is connected and the voltage output drops below **4.75V**, the PD device will restrict its current draw to avoid potentially damaging the DFP *(downward-facing port)*.
  ```
  ![image](https://user-images.githubusercontent.com/36016723/202252753-c65f00c4-3320-424b-a538-ef17bb5e4d89.png)
* Text is rendered on a new page *(codeblocks displayed using [snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) and [tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs))*:
  ```
  ??? note "Example Files"
    === "USB_desc.ino"
        ```
        --8<-- "https://raw.githubusercontent.com/felis/USB_Host_Shield_2.0/master/examples/USB_desc/USB_desc.ino"
        ```

    === "pgmstrings.h"
        ```
        --8<-- "https://raw.githubusercontent.com/felis/USB_Host_Shield_2.0/master/examples/USB_desc/pgmstrings.h"
        ```
  ```
  ![image](https://user-images.githubusercontent.com/36016723/202253055-5163bb94-df14-40b9-a0d0-d6bcf73326ff.png)

**Comment by santaimpersonator** [comment]
@mudgen I followed @cmaurer's comment, with a few modifications. I got the following result:
![image](https://user-images.githubusercontent.com/36016723/202303080-31586b96-2832-4ee1-b742-a477b04ca8dc.png)

Python packages:
* mkdocs-material            8.5.7
* mkdocs-with-pdf           0.9.3

mkdocs.yml

``` yml
extra_css:
  - stylesheets/extra.css
```

docs/stylesheets/extra.css

``` css
@media print {
  /* Adjusts positioning of admonition icon */
  .md-typeset :is(.admonition-title,summary):before {
    top: 0.6rem;
    left: 0.6rem;
  }
}
```
