### ISSUE TITLE
Ordered lists are not aligned properly when exported to PDF

### ISSUE THREAD

**Issue by theoctober19th** [orzih/mkdocs-with-pdf#94]
When building the docs using `mkdocs-with-pdf`, the ordered lists appear far left than where they are supposed to be. 

Here is what my markdown file looks like:

```md
When SFTech is being setup for the first time, there are three phases of setup that need to be completed.

1. Login with the default `admin` user and then create new password for it.
2. Set the following parameters for the system: 

    a. Impact Assessment Date  
    b. Compounding frequency to be used. (Compounding daily or compounding each interval)  
    c. Computaion model (Retrospective, Modified Retrospective or Prospective)  

These steps are described in detail in the sections that follow.
```

When viewed on browser, the alignment of ordered list is correct:
![image](https://user-images.githubusercontent.com/25663267/150052109-4c827df8-78e0-4d66-a4e0-8bd3d38a9502.png)

But when exported to PDF, the alignment of ordered list is not correct:
![image](https://user-images.githubusercontent.com/25663267/150052235-7f1700a8-bf56-4898-90b5-26a41d15d5b0.png)

Here is my `mkdocs.yml` file:
```yaml
site_name: SFTech Docs
site_url: https://sftechtepal.com/docs
site_description: The official documentation of SFTech
site_author: SFTech
copyright: Copyright &copy; 2022 Supreme Fintech Private Limited
docs_dir: docs

nav:
  - Home: index.md
  - Setup: setup.md
  - Dashboard: dashboard.md
  - Authentication: authentication.md
  - Leases: leases.md
  - Reports: reports.md
  - Approvals: approvals.md
  - User Management: user_management.md


theme:
    name: material
    logo: assets/img/sft_logo_white.svg
    favicon: assets/img/favicon.ico
    font:
        text: Nunito
    palette:
      - scheme: default
        primary: deep orange
        toggle: 
            icon: material/brightness-4 
            name: Switch to dark mode
      - scheme: slate 
        primary: deep orange
        toggle:
          icon: material/brightness-7
          name: Switch to light mode
    features:
      - toc.integrate
      - navigation.top
      - search.suggest

markdown_extensions:
    - toc:
        permalink: "#"

plugins:
  - search
  - with-pdf
```

The following were used when this issue appeared:
```
mkdocs-with-pdf: 0.9.3
macOS Big Sur 11.6
```
